### ISSUE TITLE
gopherlens is down

### ISSUE THREAD

**Issue by MineRobber9000** [dotcomboom/Pituophis#7]
Apparently, it can't find the Pituophis module?

```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, inrun_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 332, inexecute
    self.check()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, incheck
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 351, in_run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 540, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/runner/main/urls.py", line 3, in <module>
    from main import views
  File "/home/runner/main/views.py", line 11, in <module>
    import pituophis
ModuleNotFoundError: No module named 'pituophis'
exit status 1
```

**Comment by mariteaux** [comment]
lol remember when you tried abusing github to make an awful wiki we didn't need

**Comment by dotcomboom** [comment]
That's a repl.it thing. Dependencies don't tend to automatically install correctly in Django projects, so what does install it is a dirty hack that works maybe 67% of the time until they do fix that.

Pro of repl.it, it restarts automatically and on request, so when it does finally work Gopherlens gets back up and running normally without any real changes needing to be made. For example, I just checked Gopherlens and it's.. completely fine. Usually you just have to wait and try refreshing or smashing the restart button a little until it kicks into gear.

(source page: https://repl.it/@dotcomboom/gopherlens)

**Comment by dotcomboom** [comment]
That's a repl.it thing. Dependencies don't tend to automatically install correctly in Django projects, so what does install it is a dirty hack that works maybe 67% of the time until they do fix that.

Pro of repl.it, it restarts automatically and on request, so when it does finally work Gopherlens gets back up and running normally without any real changes needing to be made. For example, I just checked Gopherlens and it's.. completely fine. Usually you just have to wait and try refreshing or smashing the restart button a little until it kicks into gear.

(source page with the restart button: https://repl.it/@dotcomboom/gopherlens)
